[package]
name = "kgen_wrapper"
version = "1.0.0"
authors = []

[addresses]
kGeNAdmin="0xfb3bddd5ae0d24f06b906c914fbdd781569a38829ad909f706e70e2a49106a53"
oft="0xad5c0925a4612826ab658d99e74a8f175a128332ead54559e74bfacbb1e150b2"
[dev-addresses]

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-framework.git"
rev = "mainnet"
subdir = "aptos-framework"

[dependencies.oft]
git = "https://github.com/kgen-protocol/smartcontracts"
rev = "5cd7415aa06f173a19e1a126b5d9a135f255d9f9"
subdir = 'oft-adapter-aptos-move'

[dev-dependencies]
