[package]
name = "user_loyalty_on_chain"
version = "1.0.0"
authors = []

[addresses]
UserLoyaltyOnChain = "0xa19c666d950c3a637cd186d13be6bc6f2647a38e2f7d7ef3ec302d8ef59d0a1c"

[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosTokenObjects]
git = 'https://github.com/aptos-labs/aptos-core.git'
rev = 'mainnet'
subdir = 'aptos-move/framework/aptos-token-objects'

