/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc2771ContextUpgradableSol from "./ERC2771ContextUpgradable.sol";
export type { erc2771ContextUpgradableSol };
