[package]
name = "distributorMarket"
version = "1.0.0"
authors = []

[addresses]
# Your module’s publishing address (fill at publish time or via CLI profile)
distributorMarket = "0xbe11edfafc1198aeecc23abdc059d839ed022a94b3df5f402ef955f657167f7f"


[dependencies.AptosFramework]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-framework"

[dependencies.AptosStdlib]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-stdlib"

[dependencies.AptosTokenObjects]
git = "https://github.com/aptos-labs/aptos-core.git"
rev = "mainnet"
subdir = "aptos-move/framework/aptos-token-objects"
