/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as erc2771ContextUpgradeable from "./ERC2771ContextUpgradeable";
export type { erc2771ContextUpgradeable };
import type * as rkgenAirdropSol from "./rkgen_airdrop.sol";
export type { rkgenAirdropSol };
export type { IrKGEN } from "./IrKGEN";
export type { MockERC20 } from "./MockERC20";
export type { RKGEN } from "./RKGEN";
